apiVersion: v1
kind: Pod
metadata:
  name: avro-client
  namespace: default
spec:
  containers:
  - name: avro-client
    image: confluentinc/cp-schema-registry:5.5.1-1-ubi8
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
